[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pegma"
authors = [
    {name = "Digvijay Patankar", email = "dbpatankar@gmail.com"},
]
description = "Package for Exploratory Ground Motion Analysis"
readme = "README.md"
requires-python = ">=3.6"
keywords = ["pegma", "ground motion", "ground motion analysis", "Exploratory"]
license = {text = "GNU GPLv3"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    'pyside6', 'earthquakepy',
    'numpy', 'scipy', 'matplotlib',
]
dynamic = ["version"]

[project.scripts]
pegma = "pegma.main:run_app"

# ... other project metadata fields as specified in:
#     https://packaging.python.org/en/latest/specifications/declaring-project-metadata/